[build]
  publish = "public"

[[redirects]]
  from = "/"
  to = "/Home/index.html"
  status = 200

[[redirects]]
  from = "/Object2"
  to = "/Object2/play.html"
  status = 302
  force = true

[[redirects]]
  from = "/Object2/"
  to = "/Object2/play.html"
  status = 302
  force = true

[[redirects]]
  from = "/Object2/index.html"
  to = "/Object2/play.html"
  status = 302
  force = true
